###
# Installs nginx
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure nginx is installed
  apt: name=nginx-extras
  sudo: yes

- name: write nginx configuration for multiple subdomains
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  sudo: yes
  notify:
    - restart nginx
